list_courses:
    path:     /edit/{id}/courses
    defaults: { _controller: BackSchoolBundle:Courses:listCourses }

edit_courses:
    path:     /edit/{id}/courses/{course}
    defaults: { _controller: BackSchoolBundle:Courses:editCourses }

delete_courses:
    path:     /delete_course/{id}
    defaults: { _controller: BackSchoolBundle:Courses:deleteCourses }
    
startdate_courses:
    path:     /edit/{id}/courses/{course}/startdate
    defaults: { _controller: BackSchoolBundle:Courses:startDate }

delete_startdate_courses:
    path:     /delete_start_debut/{id}
    defaults: { _controller: BackSchoolBundle:Courses:deleteStartDate }
    
price_courses:
    path:     /edit/{id}/courses/{course}/prices
    defaults: { _controller: BackSchoolBundle:Courses:price }

delete_price_courses:
    path:     /delete_price/{id}
    defaults: { _controller: BackSchoolBundle:Courses:deletePrice }