list_courses:
    path:     /edit/{id}/courses
    defaults: { _controller: BackSchoolBundle:Courses:listCourses }

edit_courses:
    path:     /edit/{id}/courses/{course}
    defaults: { _controller: BackSchoolBundle:Courses:editCourses }

delete_courses:
    path:     /delete_course/{id}
    defaults: { _controller: BackSchoolBundle:Courses:deleteCourses }
    
startdate_courses:
    path:     /edit/{id}/courses/{course}/startdate
    defaults: { _controller: BackSchoolBundle:Courses:startDate }

generateDate_courses:
    path:     /GenerateDate/{id}
    defaults: { _controller: BackSchoolBundle:Courses:GenerateDates }

delete_all_dates:
    path:     /DeleteAllDates/{id}
    defaults: { _controller: BackSchoolBundle:Courses:deleteAllDates }

delete_startdate_courses:
    path:     /delete_start_debut/{id}
    defaults: { _controller: BackSchoolBundle:Courses:deleteStartDate }
    
price_courses:
    path:     /edit/{id}/courses/{course}/prices
    defaults: { _controller: BackSchoolBundle:Courses:price }

delete_price_courses:
    path:     /delete_price/{id}
    defaults: { _controller: BackSchoolBundle:Courses:deletePrice }
    
pathway_price_courses:
    path:     /edit/{id}/courses/{course}/pathway_prices
    defaults: { _controller: BackSchoolBundle:Courses:pathwayPrice }

delete_pathway_price_courses:
    path:     /delete_pathway_prices/{id}
    defaults: { _controller: BackSchoolBundle:Courses:deletePathwayPrice }