add_school:
    path:     /add
    defaults: { _controller: BackSchoolBundle:School:addSchool }

edit_school:
    path:     /edit/{id}
    defaults: { _controller: BackSchoolBundle:School:editSchool,id:null }

list_school:
    path:     /
    defaults: { _controller: BackSchoolBundle:School:listSchool }

delete_school:
    path:     /delete/{id}
    defaults: { _controller: BackSchoolBundle:School:deleteSchool }

edit_school:
    path:     /edit/{id}
    defaults: { _controller: BackSchoolBundle:School:editSchool }
    
enabled_school:
    path:     /enableUser/{id}
    defaults: { _controller: BackSchoolBundle:School:enableSchool}   
    
gallery_school:
    path:     /gallery/{id}
    defaults: { _controller: BackSchoolBundle:School:gallery}   
    
delete_photo:
    path:     /deletePhoto/{id}
    defaults: { _controller: BackSchoolBundle:School:deletePhoto}   
