add_school:
    path:     /add
    defaults: { _controller: BackSchoolBundle:School:addSchool }

edit_school:
    path:     /edit/{id}
    defaults: { _controller: BackSchoolBundle:School:editSchool,id:null }

list_schoolLanguage:
    path:     /listLanguage
    defaults: { _controller: BackSchoolBundle:School:listSchoolLanguage }

list_schoolPathway:
    path:     /ListPathway
    defaults: { _controller: BackSchoolBundle:School:listSchoolPathway }

delete_school_location:
    path:     /delete/{id}
    defaults: { _controller: BackSchoolBundle:School:deleteSchool }

edit_school:
    path:     /edit/{id}
    defaults: { _controller: BackSchoolBundle:School:editSchool }
    
enabled_school:
    path:     /enableSchool/{id}
    defaults: { _controller: BackSchoolBundle:School:enableSchool}   
    
    
homepage_school:
    path:     /homepageSchool/{id}
    defaults: { _controller: BackSchoolBundle:School:homepageSchool}   
    
gallery_school:
    path:     /gallery/{id}
    defaults: { _controller: BackSchoolBundle:School:gallery}   
    
delete_photo:
    path:     /deletePhoto/{id}
    defaults: { _controller: BackSchoolBundle:School:deletePhoto}   
