SchoolRouting:
    resource: "@BackSchoolBundle/Resources/config/routing/school.yml"
    prefix:   /

CoursesRouting:
    resource: "@BackSchoolBundle/Resources/config/routing/courses.yml"
    prefix:   /

AccommodationsRouting:
    resource: "@BackSchoolBundle/Resources/config/routing/accommodations.yml"
    prefix:   /

ExtrasRouting:
    resource: "@BackSchoolBundle/Resources/config/routing/extras.yml"
    prefix:   /