SchoolRouting:
    resource: "@BackSchoolBundle/Resources/config/routing/school.yml"
    prefix:   /

CoursesRouting:
    resource: "@BackSchoolBundle/Resources/config/routing/courses.yml"
    prefix:   /