back_booking_bundle:
    resource: "@BackBookingBundle/Resources/config/routing.yml"
    prefix:   /admin/booking

back_university:
    resource: "@BackUniversityBundle/Resources/config/routing.yml"
    prefix:   /admin/university

back_accommodation:
    resource: "@BackAccommodationBundle/Resources/config/routing.yml"
    prefix:   /admin/accommodation

back_general:
    resource: "@BackGeneralBundle/Resources/config/routing.yml"
    prefix:   /admin/

back_school:
    resource: "@BackSchoolBundle/Resources/config/routing.yml"
    prefix:   /admin/school

back_referentiel:
    resource: "@BackReferentielBundle/Resources/config/routing.yml"
    prefix:   /admin/ref

root:
    pattern: /
    defaults:
        _controller: FrontGeneralBundle:Default:index
        path: /{_locale}
        permanent: true    
    
front_general:
    resource: "@FrontGeneralBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements:
        _locale: en|fr|de

back_user:
    resource: "@BackUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"    

