# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_ADMIN_UNIVERSITY:       [ROLE_ADMIN]
        ROLE_ADMIN_ACCOMMODATION:       [ROLE_ADMIN]
        ROLE_ADMIN_SCHOOL:       [ROLE_ADMIN]
        ROLE_ADMIN_CONFIG:       [ROLE_ADMIN]
        ROLE_ADMIN_FRONTOFFICE:       [ROLE_ADMIN]
        ROLE_ADMIN_BOOKING:       [ROLE_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN,ROLE_ADMIN_FRONTOFFICE, ROLE_ADMIN_ACCOMMODATION,ROLE_ADMIN_SCHOOL,ROLE_ADMIN_UNIVERSITY,ROLE_ADMIN_CONFIG,ROLE_ADMIN_BOOKING]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        - { path: ^/[a-z]+/book/schools/book_validation_language_course, role: ROLE_USER }
        
        - { path: ^/admin/ref/administrator, role: ROLE_SUPER_ADMIN }
        - { path: ^/admin/ref/paypal, role: ROLE_SUPER_ADMIN }
        
        - { path: ^/admin/ref, role: ROLE_ADMIN_CONFIG }
        - { path: ^/admin/booking, role: ROLE_ADMIN_BOOKING }
        
        - { path: ^/admin/accommodation, role: ROLE_ADMIN_ACCOMMODATION }
        - { path: ^/admin/university, role: ROLE_ADMIN_UNIVERSITY }
        - { path: ^/admin/school, role: ROLE_ADMIN_SCHOOL }
        - { path: ^/admin/frontoffice, role: ROLE_ADMIN_FRONTOFFICE }
        
        - { path: ^/admin, role: ROLE_ADMIN }