BackBookingLanguageCourse:
    resource: "@BackBookingBundle/Resources/config/routing/langage_course.yml"
    prefix:   /LanguageCourse
    
BackBookingPathwayCourse:
    resource: "@BackBookingBundle/Resources/config/routing/pathway_course.yml"
    prefix:   /PathwayCourse
    
BackBookingAccommodation:
    resource: "@BackBookingBundle/Resources/config/routing/accommodation.yml"
    prefix:   /Accommodation

back_ajax_get_client_information:
    path:     /ajaxClient
    defaults: { _controller: BackBookingBundle:Default:ajaxClient }

back_ajax_get_status_information:
    path:     /ajaxStatus
    defaults: { _controller: BackBookingBundle:Default:ajaxStatus }