book_school_redirect:
    path:     /schools/book_redirect/{id}
    defaults: { _controller: FrontGeneralBundle:Booking:bookRedirectSchool}

ajax_update_price_course:
    path:     /ajax_update_price_course
    defaults: { _controller: FrontGeneralBundle:Booking:ajaxUpdatePriceCourse}

ajax_update_price_accommodation:
    path:     /ajax_update_price_accommodation
    defaults: { _controller: FrontGeneralBundle:Booking:ajaxUpdatePriceAcco}

ajax_update_duration:
    path:     /ajax_update_duration
    defaults: { _controller: FrontGeneralBundle:Booking:ajaxUpdateDuration}

book_school_step1:
    path:     /schools/Step1
    defaults: { _controller: FrontGeneralBundle:Booking:step1}

book_school_step2:
    path:     /schools/Step2
    defaults: { _controller: FrontGeneralBundle:Booking:step2}

book_school_step3:
    path:     /schools/Step3
    defaults: { _controller: FrontGeneralBundle:Booking:step3}

book_school_review:
    path:     /schools/review
    defaults: { _controller: FrontGeneralBundle:Booking:reviewCourse}



book_accommodation_redirect:
    path:     /accommodation/book_redirect/{id}
    defaults: { _controller: FrontGeneralBundle:Booking:bookRedirectAccommodation}
     
book_accommodation_step1:
    path:     /accommodation/Step1
    defaults: { _controller: FrontGeneralBundle:Booking:step1Accommodation}

ajax_update_accommodation_price_accommodation:
    path:     /ajax_update_accommodation_price_accommodation
    defaults: { _controller: FrontGeneralBundle:Booking:ajaxUpdatePriceAccommodation}

book_accommodation_review:
    path:     /accommodation/review
    defaults: { _controller: FrontGeneralBundle:Booking:reviewAccommodation}