book_school_redirect:
    path:     /schools/book_redirect/{id}
    defaults: { _controller: FrontGeneralBundle:Booking:bookRedirect}

book_school_step1:
    path:     /schools/Step1
    defaults: { _controller: FrontGeneralBundle:Booking:step1}