front_language_courses:
    path:     /list/{page}/{language}/{country}/{city}/{stars}/{sort}/{desc}/{keyword}
    defaults: { _controller: FrontGeneralBundle:LanguageCourses:list,page : 1,language : all,country : all,city: all,stars : all,sort: name,desc: asc,keyword: null }
          
front_language_courses_filtre:
    path:     /filtre/{page}/{language}/{country}/{city}/{stars}/{sort}/{desc}/{keyword}
    defaults: { _controller: FrontGeneralBundle:LanguageCourses:filtre,page : 1,language : all,country : all,city: all,stars : all,sort: name,desc: asc,keyword: null }
          
front_language_courses_details:
    path:     /school/{id}
    defaults: { _controller: FrontGeneralBundle:LanguageCourses:school}
          