front_language_courses:
    path:     /{page}/{language}/{country}/{city}/{stars}/{sort}/{desc}/{keyword}
    defaults: { _controller: FrontGeneralBundle:LanguageCourses:list,page : 1,language : all,country : all,city: all,stars : all,sort: name,desc: asc,keyword: null }
          