SchoolRoutingLanguage:
    resource: "@FrontGeneralBundle/Resources/config/routing/languageCourses.yml"
    prefix:   /LanguageCourses/

SchoolRoutingPathway:
    resource: "@FrontGeneralBundle/Resources/config/routing/programCourses.yml"
    prefix:   /PathwayCourses/

accueil:
    path:     /
    defaults: { _controller: FrontGeneralBundle:Default:index }
    
ajax_country_to_city:
    path:     /ajax_country_to_city/
    defaults: { _controller: FrontGeneralBundle:Default:ajax } 
    
front_language_courses_redirect:
    path:     /redirect_language_courses
    defaults: { _controller: FrontGeneralBundle:Default:redirectLanguage }    

front_program_courses_redirect:
    path:     /redirect_program_courses
    defaults: { _controller: FrontGeneralBundle:Default:redirectProgram }    
