SchoolRoutingLanguage:
    resource: "@FrontGeneralBundle/Resources/config/routing/languageCourses.yml"
    prefix:   /LanguageCourses/

SchoolRoutingPathway:
    resource: "@FrontGeneralBundle/Resources/config/routing/programCourses.yml"
    prefix:   /PathwayCourses/

UniversityCourses:
    resource: "@FrontGeneralBundle/Resources/config/routing/university.yml"
    prefix:   /university/

AccommodationFront:
    resource: "@FrontGeneralBundle/Resources/config/routing/accommodation.yml"
    prefix:   /accommodation/

accueil:
    path:     /
    defaults: { _controller: FrontGeneralBundle:Default:index }

contact:
    path:     /contact
    defaults: { _controller: FrontGeneralBundle:Default:contact }
    
ajax_country_to_city:
    path:     /ajax_country_to_city/
    defaults: { _controller: FrontGeneralBundle:Default:ajax } 
    
front_language_courses_redirect:
    path:     /redirect_language_courses
    defaults: { _controller: FrontGeneralBundle:Default:redirectLanguage }    

front_program_courses_redirect:
    path:     /redirect_program_courses
    defaults: { _controller: FrontGeneralBundle:Default:redirectProgram }    

front_university_redirect:
    path:     /redirect_university
    defaults: { _controller: FrontGeneralBundle:Default:redirectUniversity }    

front_accommodation_redirect:
    path:     /redirect_accommodation
    defaults: { _controller: FrontGeneralBundle:Default:redirectAccommodation }    
