SchoolRouting:
    resource: "@FrontGeneralBundle/Resources/config/routing/languageCourses.yml"
    prefix:   /languageCourses/

accueil:
    path:     /
    defaults: { _controller: FrontGeneralBundle:Default:index }
    
ajax_country_to_city:
    path:     /ajax_country_to_city/
    defaults: { _controller: FrontGeneralBundle:Default:ajax } 
