country:
    path:     /country/{id}
    defaults: { _controller: BackReferentielBundle:Referentiel:country,id:null }
delete_country:
    path:     /deletecountry/{id}
    defaults: { _controller: BackReferentielBundle:Referentiel:deleteCountry }
#********************************************************************************************************
city:
    path:     /city/{id}
    defaults: { _controller: BackReferentielBundle:Referentiel:city,id:null }
delete_city:
    path:     /deletecity/{id}
    defaults: { _controller: BackReferentielBundle:Referentiel:deleteCity }
#********************************************************************************************************
university:
    path:     /university/{id}
    defaults: { _controller: BackReferentielBundle:Referentiel:university,id:null }
delete_university:
    path:     /deleteuniversity/{id}
    defaults: { _controller: BackReferentielBundle:Referentiel:deleteUniversity }
#********************************************************************************************************
administrator:
    path:     /administrator/{id}
    defaults: { _controller: BackReferentielBundle:Referentiel:administrator,id:null }
delete_administrator:
    path:     /deleteadministrator/{id}
    defaults: { _controller: BackReferentielBundle:Referentiel:deleteAdministrator }
enabled_user:
    path:     /enableUser/{id}
    defaults: { _controller: BackReferentielBundle:Referentiel:enableUser }    
#********************************************************************************************************
language:
    path:     /language/{id}
    defaults: { _controller: BackReferentielBundle:Referentiel:language,id:null }

delete_language:
    path:     /delete_language/{id}
    defaults: { _controller: BackReferentielBundle:Referentiel:deleteLanguage }

program:
    path:     /program/{id}
    defaults: { _controller: BackReferentielBundle:Referentiel:program,id:null }

delete_program:
    path:     /delete_program/{id}
    defaults: { _controller: BackReferentielBundle:Referentiel:deleteProgram }  
    
