subjectschool:
    path:     /subjectschool/{id}
    defaults: { _controller: BackReferentielBundle:Referentiel:subjectSchool,id:null }
delete_subjectschool:
    path:     /deleteSubjectSchool/{id}
    defaults: { _controller: BackReferentielBundle:Referentiel:deleteSubjectSchool}
#********************************************************************************************************
subject:
    path:     /subject/{id}
    defaults: { _controller: BackReferentielBundle:Referentiel:subject,id:null }
delete_subject:
    path:     /deleteSubject/{id}
    defaults: { _controller: BackReferentielBundle:Referentiel:deleteSubject }
#********************************************************************************************************
qualification:
    path:     /qualification/{id}
    defaults: { _controller: BackReferentielBundle:Referentiel:qualification,id:null }
delete_qualification:
    path:     /deleteQualification/{id}
    defaults: { _controller: BackReferentielBundle:Referentiel:deleteQualification }
#********************************************************************************************************
studyMode:
    path:     /studyMode/{id}
    defaults: { _controller: BackReferentielBundle:Referentiel:studyMode,id:null }
delete_studyMode:
    path:     /deleteStudyMode/{id}
    defaults: { _controller: BackReferentielBundle:Referentiel:deleteStudyMode }
#********************************************************************************************************
level:
    path:     /level/{id}
    defaults: { _controller: BackReferentielBundle:Referentiel:level,id:null }
delete_level:
    path:     /deletelevel/{id}
    defaults: { _controller: BackReferentielBundle:Referentiel:deleteLevels }
#********************************************************************************************************
currency:
    path:     /currency/{id}
    defaults: { _controller: BackReferentielBundle:Referentiel:currency,id:null }
delete_currency:
    path:     /deleteCurrency/{id}
    defaults: { _controller: BackReferentielBundle:Referentiel:deleteCurrency }
#********************************************************************************************************
country:
    path:     /country/{id}
    defaults: { _controller: BackReferentielBundle:Referentiel:country,id:null }
delete_country:
    path:     /deletecountry/{id}
    defaults: { _controller: BackReferentielBundle:Referentiel:deleteCountry }
#********************************************************************************************************
city:
    path:     /city/{id}
    defaults: { _controller: BackReferentielBundle:Referentiel:city,id:null }
delete_city:
    path:     /deletecity/{id}
    defaults: { _controller: BackReferentielBundle:Referentiel:deleteCity }
#********************************************************************************************************
school:
    path:     /school/{id}
    defaults: { _controller: BackReferentielBundle:Referentiel:school,id:null }
delete_school:
    path:     /deleteschool/{id}
    defaults: { _controller: BackReferentielBundle:Referentiel:deleteSchool }
#********************************************************************************************************
type_accommodation:
    path:     /type_accomodation/{id}
    defaults: { _controller: BackReferentielBundle:Referentiel:typeAccomodation,id:null }
delete_type_accommodation:
    path:     /delete_type_accomodation/{id}
    defaults: { _controller: BackReferentielBundle:Referentiel:deleteTypeAccomodation, }
#********************************************************************************************************
administrator:
    path:     /administrator/{id}/{password}
    defaults: { _controller: BackReferentielBundle:Referentiel:administrator,id:null,password:null }
delete_administrator:
    path:     /deleteadministrator/{id}
    defaults: { _controller: BackReferentielBundle:Referentiel:deleteAdministrator }
enabled_user:
    path:     /enableUser/{id}
    defaults: { _controller: BackReferentielBundle:Referentiel:enableUser }    
#********************************************************************************************************
language:
    path:     /language/{id}
    defaults: { _controller: BackReferentielBundle:Referentiel:language,id:null }

delete_language:
    path:     /delete_language/{id}
    defaults: { _controller: BackReferentielBundle:Referentiel:deleteLanguage }

program:
    path:     /program/{id}
    defaults: { _controller: BackReferentielBundle:Referentiel:program,id:null }

delete_program:
    path:     /delete_program/{id}
    defaults: { _controller: BackReferentielBundle:Referentiel:deleteProgram }  
    
